#![cfg(test)]

use super::*;
use soroban_sdk::{
    symbol_short,
    testutils::{Address as _, Events as _},
    vec, Address, Bytes, Env, IntoVal, Symbol,
};

// Real UltraHonk artifacts from our circuits (Noir 1.0.0-beta.9 + bb v0.87.0),
// generated by circuits/scripts/build.sh. These exercise the actual on-chain
// BN254 verification path, not a stub.
macro_rules! fixture {
    ($t:literal, $f:literal) => {
        include_bytes!(concat!("../../../fixtures/", $t, "/", $f))
    };
}

fn setup(env: &Env) -> CredentialVerifierClient<'_> {
    let admin = Address::generate(env);
    let id = env.register(CredentialVerifier, (admin,));
    CredentialVerifierClient::new(env, &id)
}

#[test]
fn verifies_kyc() {
    let env = Env::default();
    env.mock_all_auths();
    let c = setup(&env);
    c.set_vk(&symbol_short!("kyc"), &1u32, &Bytes::from_slice(&env, fixture!("kyc", "vk")));
    assert!(c.verify_proof(
        &symbol_short!("kyc"),
        &Bytes::from_slice(&env, fixture!("kyc", "proof")),
        &Bytes::from_slice(&env, fixture!("kyc", "public_inputs")),
        &None,
    ));
}

#[test]
fn verifies_age() {
    let env = Env::default();
    env.mock_all_auths();
    let c = setup(&env);
    c.set_vk(&symbol_short!("age"), &1u32, &Bytes::from_slice(&env, fixture!("age", "vk")));
    assert!(c.verify_proof(
        &symbol_short!("age"),
        &Bytes::from_slice(&env, fixture!("age", "proof")),
        &Bytes::from_slice(&env, fixture!("age", "public_inputs")),
        &None,
    ));
}

#[test]
fn verifies_income() {
    let env = Env::default();
    env.mock_all_auths();
    let c = setup(&env);
    c.set_vk(&symbol_short!("income"), &1u32, &Bytes::from_slice(&env, fixture!("income", "vk")));
    assert!(c.verify_proof(
        &symbol_short!("income"),
        &Bytes::from_slice(&env, fixture!("income", "proof")),
        &Bytes::from_slice(&env, fixture!("income", "public_inputs")),
        &None,
    ));
}

#[test]
fn verifies_jurisdiction() {
    let env = Env::default();
    env.mock_all_auths();
    let c = setup(&env);
    c.set_vk(
        &Symbol::new(&env, "jurisdiction"),
        &1u32,
        &Bytes::from_slice(&env, fixture!("jurisdiction", "vk")),
    );
    assert!(c.verify_proof(
        &Symbol::new(&env, "jurisdiction"),
        &Bytes::from_slice(&env, fixture!("jurisdiction", "proof")),
        &Bytes::from_slice(&env, fixture!("jurisdiction", "public_inputs")),
        &None,
    ));
}

#[test]
fn verifies_employment() {
    let env = Env::default();
    env.mock_all_auths();
    let c = setup(&env);
    c.set_vk(
        &Symbol::new(&env, "employment"),
        &1u32,
        &Bytes::from_slice(&env, fixture!("employment", "vk")),
    );
    assert!(c.verify_proof(
        &Symbol::new(&env, "employment"),
        &Bytes::from_slice(&env, fixture!("employment", "proof")),
        &Bytes::from_slice(&env, fixture!("employment", "public_inputs")),
        &None,
    ));
}

#[test]
fn rejects_tampered_proof() {
    let env = Env::default();
    env.mock_all_auths();
    let c = setup(&env);
    c.set_vk(&symbol_short!("kyc"), &1u32, &Bytes::from_slice(&env, fixture!("kyc", "vk")));

    let mut bad = fixture!("kyc", "proof").to_vec();
    bad[5000] ^= 0xff;
    assert!(!c.verify_proof(
        &symbol_short!("kyc"),
        &Bytes::from_slice(&env, &bad),
        &Bytes::from_slice(&env, fixture!("kyc", "public_inputs")),
        &None,
    ));
}

#[test]
fn rejects_wrong_length_proof() {
    let env = Env::default();
    env.mock_all_auths();
    let c = setup(&env);
    c.set_vk(&symbol_short!("kyc"), &1u32, &Bytes::from_slice(&env, fixture!("kyc", "vk")));
    assert!(!c.verify_proof(
        &symbol_short!("kyc"),
        &Bytes::from_array(&env, &[0u8; 16]),
        &Bytes::from_slice(&env, fixture!("kyc", "public_inputs")),
        &None,
    ));
}

#[test]
#[should_panic]
fn set_vk_rejects_garbage() {
    let env = Env::default();
    env.mock_all_auths();
    let c = setup(&env);
    c.set_vk(&symbol_short!("kyc"), &1u32, &Bytes::from_array(&env, &[1, 2, 3]));
}

#[test]
#[should_panic]
fn panics_without_vk() {
    let env = Env::default();
    env.mock_all_auths();
    let c = setup(&env);
    c.verify_proof(
        &symbol_short!("age"),
        &Bytes::from_slice(&env, fixture!("kyc", "proof")),
        &Bytes::from_slice(&env, fixture!("kyc", "public_inputs")),
        &None,
    );
}

#[test]
fn set_vk_emits_event() {
    let env = Env::default();
    env.mock_all_auths();
    let admin = Address::generate(&env);
    let contract_id = env.register(CredentialVerifier, (admin.clone(),));
    let c = CredentialVerifierClient::new(&env, &contract_id);

    c.set_vk(
        &symbol_short!("kyc"),
        &1u32,
        &Bytes::from_slice(&env, fixture!("kyc", "vk")),
    );

    assert_eq!(
        env.events().all().filter_by_contract(&c.address),
        vec![
            &env,
            (
                c.address.clone(),
                (
                    symbol_short!("cred_ver"),
                    symbol_short!("vk_set"),
                    symbol_short!("kyc"),
                )
                    .into_val(&env),
                EventVkSet { admin: admin.clone() }.into_val(&env),
            ),
        ],
    );
}

// ── VK versioning tests (Issue #85) ──────────────────────────────────────────

/// `get_latest_version` tracks the highest version registered per type, and
/// registering an out-of-order older version never moves it backwards.
#[test]
fn latest_version_tracks_updates() {
    let env = Env::default();
    env.mock_all_auths();
    let c = setup(&env);

    c.set_vk(&symbol_short!("kyc"), &1u32, &Bytes::from_slice(&env, fixture!("kyc", "vk")));
    assert_eq!(c.get_latest_version(&symbol_short!("kyc")), 1);

    c.set_vk(&symbol_short!("kyc"), &2u32, &Bytes::from_slice(&env, fixture!("kyc", "vk")));
    assert_eq!(c.get_latest_version(&symbol_short!("kyc")), 2);

    // Out-of-order registration of an older version must not regress latest.
    c.set_vk(&symbol_short!("kyc"), &1u32, &Bytes::from_slice(&env, fixture!("kyc", "vk")));
    assert_eq!(c.get_latest_version(&symbol_short!("kyc")), 2);
}

/// After a circuit upgrade (v2 registered), an old proof verified against v1
/// still verifies — the v1 VK is retained, and `None` resolves to the new
/// latest version.
#[test]
fn old_proof_still_verifies_after_upgrade() {
    let env = Env::default();
    env.mock_all_auths();
    let c = setup(&env);

    // Register v1 and verify a proof against it explicitly.
    c.set_vk(&symbol_short!("kyc"), &1u32, &Bytes::from_slice(&env, fixture!("kyc", "vk")));
    assert!(c.verify_proof(
        &symbol_short!("kyc"),
        &Bytes::from_slice(&env, fixture!("kyc", "proof")),
        &Bytes::from_slice(&env, fixture!("kyc", "public_inputs")),
        &Some(1),
    ));

    // Upgrade to v2 — the old v1 proof must still verify (VK at (kyc,1) intact).
    c.set_vk(&symbol_short!("kyc"), &2u32, &Bytes::from_slice(&env, fixture!("kyc", "vk")));
    assert!(c.verify_proof(
        &symbol_short!("kyc"),
        &Bytes::from_slice(&env, fixture!("kyc", "proof")),
        &Bytes::from_slice(&env, fixture!("kyc", "public_inputs")),
        &Some(1),
    ));
    // And `None` now resolves to v2 (latest).
    assert!(c.verify_proof(
        &symbol_short!("kyc"),
        &Bytes::from_slice(&env, fixture!("kyc", "proof")),
        &Bytes::from_slice(&env, fixture!("kyc", "public_inputs")),
        &None,
    ));
}

/// `deprecate_version` blocks new submissions against the deprecated version.
#[test]
fn deprecated_version_rejects_new_submissions() {
    let env = Env::default();
    env.mock_all_auths();
    let c = setup(&env);

    c.set_vk(&symbol_short!("kyc"), &1u32, &Bytes::from_slice(&env, fixture!("kyc", "vk")));
    c.deprecate_version(&symbol_short!("kyc"), &1u32);

    // New submissions against the deprecated version must be rejected.
    let res = c.try_verify_proof(
        &symbol_short!("kyc"),
        &Bytes::from_slice(&env, fixture!("kyc", "proof")),
        &Bytes::from_slice(&env, fixture!("kyc", "public_inputs")),
        &Some(1),
    );
    assert!(res.is_err());
}
